repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    exclude: README.md
  - id: check-yaml
  - id: check-json
